_target_: diffsynth.model.EstimatorSynth

lr: 0.001
decay_rate: 0.99

estimator:
  _target_: diffsynth.estimator.MelEstimator
  hidden_size: 512

l_sched:
  _target_: diffsynth.schedules.ParamScheduler
  name: switch_1

sw_loss:
  _target_: diffsynth.loss.SpecWaveLoss
  mag_w: 1.0
  log_mag_w: 1.0
  fft_sizes: [64, 128, 256, 512, 1024, 2048]

synth_name: harmor_2oscfree

log_grad: true
